name: Trivy Image Scan

on:
  pull_request:
    branches:
      - main
    paths:
      - 'application/**'
  push:
    branches:
      - main
    paths:
      - 'application/**'

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Trivy
        uses: aquasecurity/trivy-action@master

      - name: Extract container images from manifests
        id: extract-images
        run: |
          # Find all images referenced in YAML files
          # Looks for `image:` in YAML (manifests, charts, etc.)
          grep -rho 'image:[ ]*[^ ]*' **/*.yaml | awk '{print $2}' | sort | uniq > images.txt
          echo "Found images:"
          cat images.txt

      - name: Run Trivy scan on all referenced images with validation
        run: |
          set -e
          while read image; do
            if [[ -n "$image" ]]; then
              echo "Scanning image $image"
              trivy image --severity HIGH,CRITICAL --ignore-unfixed --exit-code 1 "$image"
            else
              echo "Skipping empty image name"
            fi
          done < images.txt

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-report-*.sarif

      

    
